# Generated by Django 5.1.1 on 2024-11-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('conference', 'Conference'), ('concert', 'Concert'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('others', 'Others')], default='', max_length=20),
        ),
    ]
